version: '3.8'

services:
  kratos-migrate:
    image: ghcr.io/${REGISTRY}/kratos
    env_file:
      - .env
    command: migrate sql -e --yes
    depends_on:
      - postgres
    restart: on-failure

  kratos:
    image: ghcr.io/${REGISTRY}/kratos
    ports:
      - "4433:4433" # public port
      - "4434:4434" # admin port
    env_file:
      - .env
    command: ["serve", "all", "--config", "/etc/config/kratos/kratos.yml"]
    depends_on:
      - kratos-migrate
      - postgres
    restart: unless-stopped

  postgres:
    image: postgres:14
    environment:
      - POSTGRES_USER=kratos
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=kratos
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  mailslurper:
    image: oryd/mailslurper:latest-smtps
    ports:
      - "4436:4436" # UI
      - "4437:4437" # API
    restart: unless-stopped

volumes:
  postgres_data: